name: Run bandit
on:
  pull_request:
jobs:
  bandit-ci:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-bandit-install

      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install bandit

      - name: Get the bandit.yml file # the bandit.yml file must have contents: exclude_dirs: ["tests"]
        run: |
          wget https://raw.githubusercontent.com/fampay-inc/.github/main/ymls/bandit.yaml
      
      - name: Run bandit
        run: |
          poetry run bandit -r -c bandit.yml
